[build]
  functions = "netlify/functions"
  publish = "river_detective/frontend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/api/uploads/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
